export const translations: Record<string, Record<string, string>> = {
  en: {
    title: 'Contact Form',
    firstName: 'First Name',
    lastName: 'Last Name',
    displayName: 'Display Name',
    email: 'Email',
    phone: 'Phone Number',
    address: 'Address',
    role: 'Role',
    status: 'Status',
    avatar: 'Avatar',
    createdAt: 'Created At',
    updatedAt: 'Updated At',
    comments: 'Comments',
    submit: 'Submit',
    success: 'Form submitted successfully!',
    nameError: 'Name must be at least 2 characters',
    emailError: 'Invalid email format',
    phoneError: 'Invalid phone number format',
    commentsMinError: 'Comments must be at least 10 characters',
    commentsMaxError: 'Comments cannot exceed 500 characters',
    addressError: 'Address is required',
    avatarError: 'Avatar is required',
  },
  es: {
    title: 'Formulario de Contacto',
    firstName: 'Nombre',
    lastName: 'Apellido',
    displayName: 'Nombre para Mostrar',
    email: 'Correo Electrónico',
    phone: 'Número de Teléfono',
    address: 'Dirección',
    role: 'Rol',
    status: 'Estado',
    avatar: 'Avatar',
    createdAt: 'Creado En',
    updatedAt: 'Actualizado En',
    comments: 'Comentarios',
    submit: 'Enviar',
    success: '¡Formulario enviado con éxito!',
    nameError: 'El nombre debe tener al menos 2 caracteres',
    emailError: 'Formato de correo electrónico inválido',
    phoneError: 'Formato de número de teléfono inválido',
    commentsMinError: 'Los comentarios deben tener al menos 10 caracteres',
    commentsMaxError: 'Los comentarios no pueden exceder los 500 caracteres',
    addressError: 'La dirección es requerida',
    avatarError: 'El avatar es requerido',
  },
};
